.TH vi-keys 7 2010-Jan "linux" "heatherly custom tools manual"
.na

.SH NAME
yVIKEYS \- versatile, efficient, universal keyboard mini-language

.SH SUMMARY
yVIKEYS is a heatherly-specific mini-language for operating all my applications
using a pure modal keyboard interface.  while it is rooted in vim, i expect
to adapt it to every possible application.




.SH KEYBOARD MACROS (sub-mode)
.nf
.BI "char yVIKEYS_macro_init      (void *" "a_loader" ", void *" "a_saver" ");"
.BI "char yVIKEYS_macro_wrap      (void);"
.BI "char yVIKEYS_macro_reset     (void);"
.BI "char yVIKEYS_macro_rec_key   (char  " "a_key" ");"
.BI "char yVIKEYS_macro_rec_end   (void);"
.BI "char yVIKEYS_macro_define    (char *" "a_string" ");"
.BI "char yVIKEYS_macro_exec_beg  (char  " "a_name" ");"
.BI "char yVIKEYS_macro_exec_adv  (void);"
.BI "char yVIKEYS_macro_exec_key  (void);"
.BI "char yVIKEYS_macro_exec_wait (void);"
.BI "char yVIKEYS_macro_exec_play (char  " "a_key" ");"
.BI "char yVIKEYS_macro_smode     (char  " "a_major" ", char  " "a_minor" ");"
.BI "char yVIKEYS_macro_get_mode  (void);"
.BI "char yVIKEYS_macro_set_mode  (char  " "a_mode" ");"

.SH MODE
.B setup.  
when you begin the program, you must initialize the mode system.
   yVIKEYS_mode_init  ();
   yVIKEYS_mode_enter (MODE_MAP);



.SH COMMANDS
no actions, besides calling yVIKEYS_init, are required for commands to
function properly.  but, there are only two public functions associated with
the command line to add functionality.

.B yVIKEYS_cmds_add, 
temporarily adds a new command to the system, only accessable by this program
instance.  it has six arguments...
   char   cat        standard menu reference
   char*  name       full name of command
   char*  abbr       shortened form of command (if useful)
   char*  terms      description of function argument types
   void*  func       function which implements command
   char*  desc       generally available description

.B yVIKEYS_cmds_direct, 
executes a command without any interactive user input -- useful, simple,
supports batch use.  only one argument...
   char*  command    command line as it would have been typed (:)


.SH SEARCH

.B yVIKEYS_srch_init, 

.B yVIKEYS_srch_found, 
external programs feed each search result to this function to enable moving
directly between results.  only one argument...
   void*  match      pointer to result

.B yVIKEYS_srch_direct, 
executes a search without any interactive user input -- useful, simple,
supports batch use.  only one argument...
   char*  search     search line as it would have been typed (/)


.SH VIEW


.B yVIKEYS_view_init (cchar*, cchar*, cint, cint, cint)

init prepares the view environment for use and takes five arguments.  the first
two are the title and version number.  the next two are the width and height
of the main window.  the final arg is the width of the alt-view window.

.SH AUTHOR
jelloshrike at gmail dot com

.SH COLOPHON
this page is part of a documentation package meant to make use of the
heatherly tools easier and faster

