.TH vi-keys 7 2010-Jan "linux" "heatherly custom tools manual"
.na

.SH NAME
yVIKEYS \- versatile, efficient, universal keyboard mini-language

.SH SUMMARY
yVIKEYS is a heatherly-specific mini-language for operating all my applications
using a pure modal keyboard interface.  while it is rooted in vim, i expect
to adapt it to every possible application.

.SH KEYBOARD MACROS (sub-mode)
.nf
.BI "char yVIKEYS_macro_init      (void *" "a_loader" ", void *" "a_saver" ");"
.BI "char yVIKEYS_macro_wrap      (void);"
.BI "char yVIKEYS_macro_reset     (void);"
.BI "char yVIKEYS_macro_rec_key   (char  " "a_key" ");"
.BI "char yVIKEYS_macro_rec_end   (void);"
.BI "char yVIKEYS_macro_define    (char *" "a_string" ");"
.BI "char yVIKEYS_macro_exec_beg  (char  " "a_name" ");"
.BI "char yVIKEYS_macro_exec_adv  (void);"
.BI "char yVIKEYS_macro_exec_key  (void);"
.BI "char yVIKEYS_macro_exec_wait (void);"
.BI "char yVIKEYS_macro_exec_play (char  " "a_key" ");"
.BI "char yVIKEYS_macro_smode     (char  " "a_major" ", char  " "a_minor" ");"
.BI "char yVIKEYS_macro_get_mode  (void);"
.BI "char yVIKEYS_macro_set_mode  (char  " "a_mode" ");"

.SH MODE
.B setup.  
when you begin the program, you must initialize the mode system.
   yVIKEYS_mode_init  (MODE_MAP);






.SH VIEW

.SH AUTHOR
jelloshrike at gmail dot com

.SH COLOPHON
this page is part of a documentation package meant to make use of the
heatherly tools easier and faster

